"""Init alembic with user table

Revision ID: a3e28e9d0b43
Revises:
Create Date: 2024-10-01 01:55:36.446876

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a3e28e9d0b43"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
