"""add permission and groups

Revision ID: 0dbee5c8d237
Revises: 4303244cdb7a
Create Date: 2025-01-13 23:21:19.951494

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dbee5c8d237"
down_revision: str | None = "4303244cdb7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role", sa.Column("view_problems_access", sa.Boolean(), server_default="0", nullable=True)
    )
    op.add_column(
        "role", sa.Column("create_problems_access", sa.Boolean(), server_default="0", nullable=True)
    )
    op.add_column(
        "role", sa.Column("edit_problems_access", sa.Boolean(), server_default="0", nullable=True)
    )
    op.add_column(
        "role", sa.Column("delete_problems_access", sa.Boolean(), server_default="0", nullable=True)
    )
    op.add_column(
        "role",
        sa.Column(
            "view_restricted_problems_access", sa.Boolean(), server_default="0", nullable=True
        ),
    )
    op.add_column(
        "role",
        sa.Column(
            "edit_restricted_problems_access", sa.Boolean(), server_default="0", nullable=True
        ),
    )
    op.add_column(
        "role",
        sa.Column(
            "delete_restricted_problems_access", sa.Boolean(), server_default="0", nullable=True
        ),
    )
    op.add_column(
        "role", sa.Column("make_submission_access", sa.Boolean(), server_default="0", nullable=True)
    )
    op.add_column(
        "role",
        sa.Column("view_own_submissions_access", sa.Boolean(), server_default="0", nullable=True),
    )
    op.add_column(
        "role",
        sa.Column("view_others_submission_access", sa.Boolean(), server_default="0", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role", "view_others_submission_access")
    op.drop_column("role", "view_own_submissions_access")
    op.drop_column("role", "make_submission_access")
    op.drop_column("role", "delete_restricted_problems_access")
    op.drop_column("role", "edit_restricted_problems_access")
    op.drop_column("role", "view_restricted_problems_access")
    op.drop_column("role", "delete_problems_access")
    op.drop_column("role", "edit_problems_access")
    op.drop_column("role", "create_problems_access")
    op.drop_column("role", "view_problems_access")
    # ### end Alembic commands ###
