"""add group permissions

Revision ID: 2b103945f96c
Revises: d21368c7be1e
Create Date: 2025-01-25 14:41:29.020267

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b103945f96c"
down_revision: str | None = "d21368c7be1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("group", "project_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column(
        "role",
        sa.Column(
            "view_supervised_submission_access", sa.Boolean(), server_default="0", nullable=True
        ),
    )
    op.add_column(
        "role", sa.Column("view_groups_access", sa.Boolean(), server_default="0", nullable=True)
    )
    op.add_column(
        "role", sa.Column("create_groups_access", sa.Boolean(), server_default="0", nullable=True)
    )
    op.add_column(
        "role", sa.Column("edit_groups_access", sa.Boolean(), server_default="0", nullable=True)
    )
    op.add_column(
        "role", sa.Column("delete_groups_access", sa.Boolean(), server_default="0", nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role", "delete_groups_access")
    op.drop_column("role", "edit_groups_access")
    op.drop_column("role", "create_groups_access")
    op.drop_column("role", "view_groups_access")
    op.drop_column("role", "view_supervised_submission_access")
    op.alter_column("group", "project_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
