"""add organisation user models

Revision ID: 4a194a413981
Revises: b48765e2c35a
Create Date: 2025-01-30 15:36:38.114924

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a194a413981"
down_revision: str | None = "b48765e2c35a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisation_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("EDITOR", "OBSERVER", name="organisationrole"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_organisation_member_organisation_id_organisation"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_organisation_member_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisation_member")),
    )
    op.create_table(
        "organisationinvitationkey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("EDITOR", "OBSERVER", name="organisationrole"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_organisationinvitationkey_organisation_id_organisation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisationinvitationkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organisationinvitationkey")
    op.drop_table("organisation_member")
    # ### end Alembic commands ###
