"""fix: typo 'view_own_submission_access'

Revision ID: 5f64d18cfd27
Revises: fb0ee4b99169
Create Date: 2025-01-22 15:10:06.712650

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f64d18cfd27"
down_revision: str | None = "fb0ee4b99169"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role",
        sa.Column("view_own_submission_access", sa.Boolean(), server_default="0", nullable=True),
    )
    op.drop_column("role", "view_own_submissions_access")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role",
        sa.Column(
            "view_own_submissions_access",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("role", "view_own_submission_access")
    # ### end Alembic commands ###
