"""delete group models

Revision ID: 68c60f4de304
Revises: dc835ebeb738
Create Date: 2025-01-24 16:29:45.012780

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "68c60f4de304"
down_revision: str | None = "dc835ebeb738"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
