"""Nullable submission_id and user_id for task_attempt

Revision ID: 778d8a7bc392
Revises: 3afe016957f9
Create Date: 2024-12-12 17:37:27.222298

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "778d8a7bc392"
down_revision: str | None = "3afe016957f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission", "status")
    op.drop_column("submission", "started_at")
    op.drop_column("submission", "other_fields")
    op.add_column("task_attempt", sa.Column("user_id", sa.Integer(), nullable=False))
    op.alter_column("task_attempt", "submission_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key("task_attempt_user_id_user", "task_attempt", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("task_attempt_user_id_user", "task_attempt", type_="foreignkey")
    op.alter_column("task_attempt", "submission_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("task_attempt", "user_id")
    op.add_column(
        "submission",
        sa.Column(
            "other_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "submission",
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "submission",
        sa.Column(
            "status",
            postgresql.ENUM("Pending", "Ok", name="submissionstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
