"""initialize permissions

Revision ID: 8552946a2abb
Revises: 412a1b074446
Create Date: 2025-02-02 19:47:53.318225

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8552946a2abb"
down_revision: str | None = "412a1b074446"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role",
        sa.Column("view_problems_access", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "role",
        sa.Column("create_problems_access", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "role",
        sa.Column("edit_problems_access", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "role",
        sa.Column("delete_problems_access", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "role",
        sa.Column(
            "view_restricted_problems_access", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "role",
        sa.Column(
            "edit_restricted_problems_access", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "role",
        sa.Column(
            "delete_restricted_problems_access",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "role",
        sa.Column("make_submission_access", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "role",
        sa.Column(
            "view_own_submission_access", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "role",
        sa.Column(
            "view_others_submission_access", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role", "view_others_submission_access")
    op.drop_column("role", "view_own_submission_access")
    op.drop_column("role", "make_submission_access")
    op.drop_column("role", "delete_restricted_problems_access")
    op.drop_column("role", "edit_restricted_problems_access")
    op.drop_column("role", "view_restricted_problems_access")
    op.drop_column("role", "delete_problems_access")
    op.drop_column("role", "edit_problems_access")
    op.drop_column("role", "create_problems_access")
    op.drop_column("role", "view_problems_access")
    # ### end Alembic commands ###
