"""add organisation member models

Revision ID: 91ad33d0eaa1
Revises: b48765e2c35a
Create Date: 2025-01-30 17:19:58.007712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91ad33d0eaa1"
down_revision: str | None = "b48765e2c35a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisation_invitation_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "OBSERVER", name="organisationrole"), nullable=False),
        sa.Column("key", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_organisation_invitation_key_organisation_id_organisation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisation_invitation_key")),
        sa.UniqueConstraint("key", name=op.f("uq_organisation_invitation_key_key")),
    )
    op.create_table(
        "organisation_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "OBSERVER", name="organisationrole"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_organisation_member_organisation_id_organisation"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_organisation_member_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisation_member")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organisation_member")
    op.drop_table("organisation_invitation_key")
    op.execute("DROP TYPE organisationrole")
    # ### end Alembic commands ###
