"""add restricted bool

Revision ID: dc835ebeb738
Revises: 5f64d18cfd27
Create Date: 2025-01-23 16:47:13.113916

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc835ebeb738"
down_revision: str | None = "5f64d18cfd27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problem", sa.Column("restricted", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problem", "restricted")
    # ### end Alembic commands ###
