"""fix: make username unique

Revision ID: fb0ee4b99169
Revises: 0dbee5c8d237
Create Date: 2025-01-21 22:49:46.491776

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb0ee4b99169"
down_revision: str | None = "0dbee5c8d237"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    # ### end Alembic commands ###
